wip: overhaul
canonical/bootstack-actions pull request #32
Opened 2023-09-05 17:44 UTC by mert-kirpici

2023-09-07 12:25 UTC, rgildein reviewed
Overall it looks good to me, but I'm not sure if it's ok to remove lint, unit and functional tests from release workflows (charm and snap). What do you think @esunar? It should be fine, since we cannot merge anything directly to main or master branch, but maybe PR will be merged without passing those tests.

2023-09-07 15:35 UTC, mert-kirpici commented
> Overall it looks good to me, but I'm not sure if it's ok to remove lint, unit and functional tests from release workflows (charm and snap). What do you think @esunar? It should be fine, since we cannot merge anything directly to main or master branch, but maybe PR will be merged without passing those tests.

I was thinking we reuse the check(lint-unit-func) workflow in the release workflow on the calling side(project) by adding workflow_call to `pr.yaml` to make it reusable and then adding this to the `release.yaml`:
```
jobs:
  tests:
    uses: ./.github/workflows/pr.yaml

  snap-release:
    uses: canonical/bootstack-actions/.github/workflows/snap-release.yaml@v2
    needs: tests
    ...
```

tested in private repo. seems to work fine.

2023-09-07 15:53 UTC, mert-kirpici commented
> That's not nice (calling PR not in PR :) ), but it make sense.

we can rename it to `check.yaml` ? it is a check pipeline afterall

2023-09-08 02:48 UTC, agileshaw requested changes
I like the overall changes. Just one wording change suggested inline. 

About the on-going discussion, I think including tests in the release workflow is necessary because passing tests in PR doesn't guarantee an issue-free merge. The idea of putting lint-unit-func tests in a `check.yaml` file (or maybe naming it `ci-validation.yaml`) which then be used in both PR and release workflow sounds nice and clean.

2023-09-08 02:48 UTC, agileshaw commented on .github/workflows/func.yaml
> +        default: "<4"
We need to change the description if using `tox<4` as default. The current wording gives the wrong impression that "no user input == unspecified".

2023-09-11 12:12 UTC, rgildein approved these changes
Let's try it. Thanks

2023-09-11 13:44 UTC, esunar approved these changes

2023-09-11 14:24 UTC, agileshaw approved these changes
Looks good, thanks

2023-09-11 14:41 UTC, merged