ci: Show juju information
canonical/bootstack-actions pull request #36
Opened 2023-10-23 09:52 UTC by jneo8

2023-10-23 16:50 UTC, rgildein requested changes

2023-10-25 03:07 UTC, jneo8 commented on .github/workflows/_func.yaml
> +          juju controllers
Updated

2023-10-27 02:15 UTC, jneo8 commented on .github/workflows/_func.yaml
> +          juju controllers
Hi @rgildein, can I have second review from you?

2023-10-27 02:21 UTC, agileshaw approved these changes

2023-10-27 04:03 UTC, Pjack approved these changes
LGTM

2023-10-27 13:01 UTC, rgildein approved these changes

2023-10-30 02:05 UTC, merged