add base sonar integration
canonical/bootstack-actions pull request #9
Opened 2023-03-10 14:15 UTC by rgildein

Add base sonar integration. 
I also added it to the [bootstack-charms-spec](https://code.launchpad.net/~rgildein/bootstack-charms-spec/+git/bootstack-charms-spec/+merge/438698).

2023-03-13 08:00 UTC, esunar requested changes

2023-03-13 08:05 UTC, rgildein commented on .github/workflows/test-sonar.yaml
> +name: SonarCloud
Do we have such .md file? Would it not better to have these files in `bootstack-charms-spec`?

2023-03-14 06:10 UTC, esunar commented on .github/workflows/test-sonar.yaml
> +name: SonarCloud
https://pastebin.canonical.com/p/FGX2w3ymKR/

2023-04-24 08:49 UTC, rgildein commented on .github/workflows/test-sonar.yaml
> +name: SonarCloud
I updated it little bit and added it to README.md.

2023-04-24 09:58 UTC, esunar approved these changes

2023-04-24 13:48 UTC, Pjack approved these changes
sonar.yaml is copied from https://github.com/canonical/charm-prometheus-juju-exporter/blob/main/.github/workflows/sonar.yml, so I'm good with it and skip the review.

About the README.md, I am thinking that we should put the document into google drive share folder. Some diagram and snapshots are useful. But right now, simple description here is also good.

2023-04-24 14:25 UTC, merged